INFO:discord.client:logging in using static token
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the IDENTIFY payload.
INFO:discord.gateway:Shard ID None has connected to Gateway: gateway-prd-main-7ns0, discord-sessions-prd-1-19 (Session ID: 80d60bd6d19082d1c9c35158dacee255).
INFO:root:Logging in as:FourthBot : 562473668362502176
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\__init__.py", line 41, in autodetect
    from . import file_cache
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/sheets/v4/rest
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Bank%20Chart%21A%3AB?alt=json
INFO:root:Received |bank| command from |Father Fujimoto|
INFO:root:Received |oof| command from |Scarybone|
INFO:root:Received |oof| command from |Scarybone|
INFO:root:Received |spell| command from |Shadow Creature 22|
INFO:discord.gateway:Websocket closed with 1006 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 80d60bd6d19082d1c9c35158dacee255 under trace gateway-prd-main-nl9w, discord-sessions-prd-1-19.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Character%20Chart%21A2%3AG13?alt=json
INFO:root:Received |current| command from |Shadow Creature 22|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Character%20Chart%21A2%3AG13?alt=json
INFO:root:Received |current| command from |Shadow Creature 22|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Character%20Chart%21A2%3AG13?alt=json
INFO:root:Received |current| command from |Shadow Creature 22|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Character%20Chart%21A2%3AG13?alt=json
INFO:root:Received |current| command from |Shadow Creature 22|
INFO:root:Received |help| command from |Scarybone|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Character%20Chart%21A2%3AG13?alt=json
INFO:root:Received |xp| command from |Scarybone|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Character%20Chart%21A2%3AG13?alt=json
INFO:root:Received |current| command from |Scarybone|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Character%20Chart%21A2%3AG13?alt=json
INFO:root:Received |current| command from |Scarybone|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Character%20Chart%21A2%3AG13?alt=json
INFO:root:Received |current| command from |Scarybone|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Character%20Chart%21A2%3AG13?alt=json
INFO:root:Received |current| command from |Shadow Creature 22|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Character%20Chart%21A2%3AG13?alt=json
INFO:root:Received |current| command from |Shadow Creature 22|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Character%20Chart%21A2%3AG13?alt=json
INFO:root:Received |current| command from |Shadow Creature 22|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Character%20Chart%21A2%3AG13?alt=json
INFO:root:Received |current| command from |Shadow Creature 22|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Bank%20Chart%21A%3AB?alt=json
INFO:root:Received |bank| command from |Shadow Creature 22|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Bank%20Chart%21A%3AB?alt=json
INFO:root:Received |bank| command from |Shadow Creature 22|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Character%20Chart%21A2%3AG13?alt=json
INFO:root:Received |current| command from |Shadow Creature 22|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Character%20Chart%21A2%3AG13?alt=json
INFO:root:Received |xp| command from |Shadow Creature 22|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Bank%20Chart%21A%3AB?alt=json
INFO:root:Received |bank| command from |Shadow Creature 22|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Bank%20Chart%21A%3AB?alt=json
INFO:root:Received |bank| command from |Shadow Creature 22|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Bank%20Chart%21A%3AB?alt=json
INFO:root:Received |bank| command from |Shadow Creature 22|
INFO:discord.gateway:Websocket closed with 1006 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 80d60bd6d19082d1c9c35158dacee255 under trace gateway-prd-main-4v5l, discord-sessions-prd-1-19.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1001 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 80d60bd6d19082d1c9c35158dacee255 under trace gateway-prd-main-sd54, discord-sessions-prd-1-19.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1001 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 80d60bd6d19082d1c9c35158dacee255 under trace gateway-prd-main-zml2, discord-sessions-prd-1-19.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1001 (CloudFlare WebSocket proxy restarting), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 80d60bd6d19082d1c9c35158dacee255 under trace gateway-prd-main-1kbg, discord-sessions-prd-1-19.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1001 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 80d60bd6d19082d1c9c35158dacee255 under trace gateway-prd-main-qqpb, discord-sessions-prd-1-19.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1006 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 80d60bd6d19082d1c9c35158dacee255 under trace gateway-prd-main-btnw, discord-sessions-prd-1-19.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1001 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 80d60bd6d19082d1c9c35158dacee255 under trace gateway-prd-main-zbvt, discord-sessions-prd-1-19.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1006 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 80d60bd6d19082d1c9c35158dacee255 under trace gateway-prd-main-4zwg, discord-sessions-prd-1-19.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1001 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 80d60bd6d19082d1c9c35158dacee255 under trace gateway-prd-main-9lw4, discord-sessions-prd-1-19.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1001 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 80d60bd6d19082d1c9c35158dacee255 under trace gateway-prd-main-nm18, discord-sessions-prd-1-19.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1006 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 80d60bd6d19082d1c9c35158dacee255 under trace gateway-prd-main-s6rf, discord-sessions-prd-1-19.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1001 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 80d60bd6d19082d1c9c35158dacee255 under trace gateway-prd-main-vk5t, discord-sessions-prd-1-19.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1006 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 80d60bd6d19082d1c9c35158dacee255 under trace gateway-prd-main-n8fr, discord-sessions-prd-1-19.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1001 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 80d60bd6d19082d1c9c35158dacee255 under trace gateway-prd-main-4pzd, discord-sessions-prd-1-19.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1001 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 80d60bd6d19082d1c9c35158dacee255 under trace gateway-prd-main-wnbm, discord-sessions-prd-1-19.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1001 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 80d60bd6d19082d1c9c35158dacee255 under trace gateway-prd-main-mnvz, discord-sessions-prd-1-19.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1001 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 80d60bd6d19082d1c9c35158dacee255 under trace gateway-prd-main-lvnr, discord-sessions-prd-1-19.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1001 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 80d60bd6d19082d1c9c35158dacee255 under trace gateway-prd-main-tlnm, discord-sessions-prd-1-19.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1006 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 80d60bd6d19082d1c9c35158dacee255 under trace gateway-prd-main-jxb6, discord-sessions-prd-1-19.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1006 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 80d60bd6d19082d1c9c35158dacee255 under trace gateway-prd-main-c27q, discord-sessions-prd-1-19.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:root:Received |spell| command from |Scarybone|
INFO:discord.gateway:Websocket closed with 1001 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 80d60bd6d19082d1c9c35158dacee255 under trace gateway-prd-main-4pzd, discord-sessions-prd-1-19.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1001 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 80d60bd6d19082d1c9c35158dacee255 under trace gateway-prd-main-9ljs, discord-sessions-prd-1-19.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1001 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 80d60bd6d19082d1c9c35158dacee255 under trace gateway-prd-main-4d8g, discord-sessions-prd-1-19.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
WARNING:discord.gateway:Can't keep up, websocket is 12.1s behind.
INFO:discord.gateway:Websocket closed with 1001 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 80d60bd6d19082d1c9c35158dacee255 under trace gateway-prd-main-4d8g, discord-sessions-prd-1-19.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1006 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 80d60bd6d19082d1c9c35158dacee255 under trace gateway-prd-main-sjq5, discord-sessions-prd-1-19.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1006 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 80d60bd6d19082d1c9c35158dacee255 under trace gateway-prd-main-7fmj, discord-sessions-prd-1-19.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1001 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 80d60bd6d19082d1c9c35158dacee255 under trace gateway-prd-main-v2qs, discord-sessions-prd-1-19.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1001 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 80d60bd6d19082d1c9c35158dacee255 under trace gateway-prd-main-8p3p, discord-sessions-prd-1-19.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1006 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 80d60bd6d19082d1c9c35158dacee255 under trace gateway-prd-main-kvc9, discord-sessions-prd-1-19.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1006 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None session has been invalidated.
INFO:discord.gateway:Shard ID None has sent the IDENTIFY payload.
INFO:discord.gateway:Shard ID None has connected to Gateway: gateway-prd-main-g6sb, discord-sessions-prd-1-18 (Session ID: 2e667204bcc7f6f2563579b5eba4ed92).
INFO:root:Logging in as:FourthBot : 562473668362502176
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1006 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 2e667204bcc7f6f2563579b5eba4ed92 under trace gateway-prd-main-ppdb, discord-sessions-prd-1-18.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1006 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 2e667204bcc7f6f2563579b5eba4ed92 under trace gateway-prd-main-g6sb, discord-sessions-prd-1-18.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:root:Received |roll| command from |Scarybone|
INFO:root:Received |roll| command from |Scarybone|
INFO:root:Received |roll| command from |Scarybone|
INFO:root:Received |roll| command from |Scarybone|
INFO:discord.gateway:Websocket closed with 1006 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 2e667204bcc7f6f2563579b5eba4ed92 under trace gateway-prd-main-tn9l, discord-sessions-prd-1-18.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1001 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 2e667204bcc7f6f2563579b5eba4ed92 under trace gateway-prd-main-n8fr, discord-sessions-prd-1-18.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1001 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 2e667204bcc7f6f2563579b5eba4ed92 under trace gateway-prd-main-8mf7, discord-sessions-prd-1-18.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1006 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 2e667204bcc7f6f2563579b5eba4ed92 under trace gateway-prd-main-q9hs, discord-sessions-prd-1-18.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1006 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 2e667204bcc7f6f2563579b5eba4ed92 under trace gateway-prd-main-nn6t, discord-sessions-prd-1-18.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1006 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 2e667204bcc7f6f2563579b5eba4ed92 under trace gateway-prd-main-4v5l, discord-sessions-prd-1-18.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1006 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 2e667204bcc7f6f2563579b5eba4ed92 under trace gateway-prd-main-nnbg, discord-sessions-prd-1-18.
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1006 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 2e667204bcc7f6f2563579b5eba4ed92 under trace ["gateway-prd-main-pdkv",{"micros":669,"calls":["discord-sessions-prd-1-18"]}].
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1006 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 2e667204bcc7f6f2563579b5eba4ed92 under trace ["gateway-prd-main-9zsp",{"micros":1614,"calls":["discord-sessions-prd-1-18"]}].
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1006 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 2e667204bcc7f6f2563579b5eba4ed92 under trace ["gateway-prd-main-0qnv",{"micros":2886,"calls":["discord-sessions-prd-1-18"]}].
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1006 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 2e667204bcc7f6f2563579b5eba4ed92 under trace ["gateway-prd-main-bq6t",{"micros":3356,"calls":["discord-sessions-prd-1-18",{"micros":11}]}].
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1006 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 2e667204bcc7f6f2563579b5eba4ed92 under trace ["gateway-prd-main-5kmd",{"micros":2591,"calls":["discord-sessions-prd-1-18",{"micros":17}]}].
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1000 (), cannot reconnect.
ERROR:discord.client:Attempting a reconnect in 0.05s
Traceback (most recent call last):
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\gateway.py", line 464, in poll_event
    msg = await self.recv()
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\protocol.py", line 350, in recv
    yield from self.ensure_open()
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\protocol.py", line 512, in ensure_open
    self.close_code, self.close_reason) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000 (OK), no reason

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 431, in connect
    await self._connect()
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 395, in _connect
    await self.ws.poll_event()
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\gateway.py", line 472, in poll_event
    raise ConnectionClosed(exc, shard_id=self.shard_id) from exc
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 1000 (OK), no reason
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the IDENTIFY payload.
INFO:discord.gateway:Shard ID None has connected to Gateway: ["gateway-prd-main-cfv7",{"micros":64243,"calls":["discord-sessions-prd-1-3",{"micros":59939,"calls":["start_session",{"micros":57899,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: c4a1b6c0d99492e32f6b7de40cda6e0b).
INFO:root:Logging in as:FourthBot : 562473668362502176
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.gateway:Websocket closed with 1001 (), attempting a reconnect.
INFO:discord.client:Got a request to RESUME the websocket.
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the RESUME payload.
INFO:discord.gateway:Shard ID None has successfully RESUMED session c4a1b6c0d99492e32f6b7de40cda6e0b under trace ["gateway-prd-main-ch39",{"micros":1137,"calls":["discord-sessions-prd-1-3",{"micros":15}]}].
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.client:logging in using static token
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the IDENTIFY payload.
INFO:discord.gateway:Shard ID None has connected to Gateway: ["gateway-prd-main-q6rm",{"micros":36895,"calls":["discord-sessions-prd-1-21",{"micros":35237,"calls":["start_session",{"micros":28948,"calls":["api-prd-main-mxd1",{"micros":24979,"calls":["get_user",{"micros":2397},"add_authorized_ip",{"micros":5},"get_guilds",{"micros":1771},"coros_wait",{"micros":3}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":4289,"calls":[]}]}]}] (Session ID: 659e6baef8435ee3829beb9b59d132d7).
INFO:root:Logging in as:FourthBot : 562473668362502176
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\__init__.py", line 41, in autodetect
    from . import file_cache
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/sheets/v4/rest
INFO:root:Received |hi| command from |Scarybone|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Character%20Chart%21A2%3AG13?alt=json
INFO:root:Received |current| command from |Scarybone|
INFO:root:Received |help| command from |Scarybone|
INFO:root:Received |test| command from |Scarybone|
INFO:root:Received |help| command from |Scarybone|
INFO:root:Received |help| command from |Scarybone|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Bank%20Chart%21A%3AB?alt=json
INFO:root:Received |bank| command from |Scarybone|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Bank%20Chart%21A%3AB?alt=json
INFO:root:Received |bank| command from |Scarybone|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Character%20Chart%21A2%3AG13?alt=json
INFO:root:Received |current| command from |Scarybone|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Character%20Chart%21A2%3AG13?alt=json
INFO:root:Received |current| command from |Scarybone|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Character%20Chart%21A2%3AG13?alt=json
INFO:root:Received |current| command from |Scarybone|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Character%20Chart%21A2%3AG13?alt=json
INFO:root:Received |current| command from |Scarybone|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Character%20Chart%21A2%3AG13?alt=json
INFO:root:Received |current| command from |Scarybone|
INFO:discord.client:logging in using static token
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the IDENTIFY payload.
INFO:discord.gateway:Shard ID None has connected to Gateway: ["gateway-prd-main-4dm2",{"micros":32171,"calls":["discord-sessions-prd-1-13",{"micros":29887,"calls":["start_session",{"micros":26773,"calls":["api-prd-main-9gzq",{"micros":23809,"calls":["get_user",{"micros":1984},"add_authorized_ip",{"micros":5},"get_guilds",{"micros":1637},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":241,"calls":[]}]}]}] (Session ID: 8f08fb1265b244a9851880a674b99847).
INFO:root:Logging in as:FourthBot : 562473668362502176
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\__init__.py", line 41, in autodetect
    from . import file_cache
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/sheets/v4/rest
INFO:root:Received |gattaca| command from |Scarybone|
INFO:discord.client:logging in using static token
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the IDENTIFY payload.
INFO:discord.gateway:Shard ID None has connected to Gateway: ["gateway-prd-main-gjhc",{"micros":32154,"calls":["discord-sessions-prd-1-5",{"micros":30381,"calls":["start_session",{"micros":28289,"calls":["api-prd-main-ckbb",{"micros":23675,"calls":["get_user",{"micros":1764},"add_authorized_ip",{"micros":5},"get_guilds",{"micros":4360},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: a365e795ef100fdb7d313cb1e10b554c).
INFO:root:Logging in as:FourthBot : 562473668362502176
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\__init__.py", line 41, in autodetect
    from . import file_cache
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/sheets/v4/rest
INFO:root:Received |gattaca| command from |HUNK|
INFO:discord.client:logging in using static token
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the IDENTIFY payload.
INFO:discord.gateway:Shard ID None has connected to Gateway: ["gateway-prd-main-n4w5",{"micros":26121,"calls":["discord-sessions-prd-1-24",{"micros":24014,"calls":["start_session",{"micros":22167,"calls":["api-prd-main-45vp",{"micros":18214,"calls":["get_user",{"micros":1962},"add_authorized_ip",{"micros":9},"get_guilds",{"micros":2089},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":1030,"calls":[]}]}]}] (Session ID: 5f84e737277e86b27f075cb39c25fcfc).
INFO:root:Logging in as:FourthBot : 562473668362502176
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\__init__.py", line 41, in autodetect
    from . import file_cache
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/sheets/v4/rest
INFO:root:Received |gattaca| command from |Scarybone|
INFO:googleapiclient.discovery:URL being requested: POST https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Bank%20Tracker%21A%3AG:append?valueInputOption=USER_ENTERED&alt=json
INFO:root:Received |bonus| command from |Scarybone|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Bank%20Chart%21A%3AB?alt=json
INFO:root:Received |bank| command from |Scarybone|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Bank%20Chart%21A%3AB?alt=json
INFO:root:Received |bank| command from |HUNK|
INFO:discord.client:logging in using static token
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the IDENTIFY payload.
INFO:discord.gateway:Shard ID None has connected to Gateway: ["gateway-prd-main-006d",{"micros":20632,"calls":["discord-sessions-prd-1-3",{"micros":18689,"calls":["start_session",{"micros":16901,"calls":["api-prd-main-l9sr",{"micros":14065,"calls":["get_user",{"micros":2001},"add_authorized_ip",{"micros":5},"get_guilds",{"micros":1678},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":850,"calls":[]}]}]}] (Session ID: af4ca29b6c5873d6f2831250d5c07307).
INFO:root:Logging in as:FourthBot : 562473668362502176
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\__init__.py", line 41, in autodetect
    from . import file_cache
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/sheets/v4/rest
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Character%20Chart%21A2%3AG13?alt=json
INFO:root:Received |current| command from |HUNK|
INFO:root:Received |help| command from |Scarybone|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Character%20Chart%21A2%3AG13?alt=json
INFO:root:Received |xp| command from |Scarybone|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Character%20Chart%21A2%3AG13?alt=json
INFO:root:Received |xp| command from |Scarybone|
INFO:discord.client:logging in using static token
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
INFO:discord.gateway:Shard ID None has sent the IDENTIFY payload.
INFO:discord.gateway:Shard ID None has connected to Gateway: ["gateway-prd-main-f2d3",{"micros":23760,"calls":["discord-sessions-prd-1-19",{"micros":21622,"calls":["start_session",{"micros":20732,"calls":["api-prd-main-gdvr",{"micros":17543,"calls":["get_user",{"micros":2044},"add_authorized_ip",{"micros":5},"get_guilds",{"micros":1885},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: d3b0602db29dd3404eae4766d0d5f571).
INFO:root:Logging in as:FourthBot : 562473668362502176
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\__init__.py", line 41, in autodetect
    from . import file_cache
  File "C:\Users\Salanski\AppData\Local\Programs\Python\Python36\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/sheets/v4/rest
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Character%20Chart%21A2%3AG14?alt=json
INFO:root:Received |xp| command from |Scarybone|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Bank%20Chart%21A%3AB?alt=json
INFO:root:Received |bank| command from |HUNK|
INFO:root:Received |hi| command from |Scarybone|
INFO:root:Received |hi| command from |ScarletRose107|
INFO:root:Received |oof| command from |Scarybone|
INFO:googleapiclient.discovery:URL being requested: GET https://sheets.googleapis.com/v4/spreadsheets/1dVZlsgtbUq0MGWV4kBg7m6Kwv2kQtbBd88KFHq9uumo/values/Bank%20Chart%21A%3AB?alt=json
INFO:root:Received |bank| command from |HUNK|
